name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: marijnvdwerf/re-pebble-build-tools:basic

    steps:
    - uses: actions/checkout@v2

    - run: apt-get update --yes
    - run: apt-get install --no-install-recommends --yes cmake make

    - name: Create Build Environment
      run: mkdir $GITHUB_WORKSPACE/build
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=/usr/xcc/arm-none-eabi/bin/arm-none-eabi-gcc -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_SYSTEM_PROCESSOR=arm
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
    - name: Validate built bootloader
      run: echo "836b23d0c03775bfb137c41784e9e802  bootrom/bootrom.bin" | md5sum -c -
      working-directory: ${{github.workspace}}/build
