name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      # These should probably be moved to a Dockerfile
    - name: Download Pebble SDK
      run: wget -O pebble-sdk.tar.bz2 https://developer.rebble.io/s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.5-linux64.tar.bz2
    - name: Extract Pebble SDK
      run: tar -jxf pebble-sdk.tar.bz2

    - name: Create Build Environment
      run: mkdir ${{github.workspace}}/build
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$GITHUB_WORKSPACE/pebble-sdk-4.5-linux64/arm-cs-tools/bin/arm-none-eabi-gcc -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_SYSTEM_PROCESSOR=arm
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
    - name: Validate built bootloader
      run: echo "836b23d0c03775bfb137c41784e9e802  bootrom/bootrom.bin" | md5sum -c -
      working-directory: ${{github.workspace}}/build
